name: 'Chisel Installer'
description: 'Installs Canonical Chisel into GitHub Actions'
author: 'shyim'
branding:
  color: 'blue'
  icon: 'download'
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd /tmp
        CHISEL_VERSION=$(curl https://api.github.com/repos/canonical/chisel/releases/latest | jq '.tag_name' -r)
        CHISEL_ARCH=$(dpkg --print-architecture)
        wget https://github.com/canonical/chisel/releases/download/${CHISEL_VERSION}/chisel_${CHISEL_VERSION}_linux_${CHISEL_ARCH}.tar.gz
        tar xfv chisel_${CHISEL_VERSION}_linux_${CHISEL_ARCH}.tar.gz
        sudo mv chisel /usr/local/bin/chisel
